version: '3'

services:
  db:
    image: postgres:alpine
    container_name: control-tower-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'


  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: control-tower-app
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  db_data:
